server:
  port: 8010
spring:
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  application:
    name: image-service
  jpa:
    hibernate:
      ddl-auto: create-drop
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    properties:
      hibernate:
        default_schema: gallery
  liquibase:
    change-log: classpath:/db/changelog/app-changelog.xml
  datasource:
    driver-class-name: ${DB_DRIVER:org.postgresql.Driver}
    url: ${DB_URL:jdbc:postgresql://localhost:5433/images}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:password}

app:
  s3:
    endpoint: http://localhost:4566
    bucket-name: images-bucket
    region: us-east-1
    access-key: test
    secret-key: test
